import { type BetterSQLite3Database } from "drizzle-orm/better-sqlite3";
import { challengeGames, challengeItems } from "./schema";

// ── static seed data (mirrors the former JSON config files) ──────────────────

const games = [
  {
    slug: "twelve-caesars",
    gameType: "chronology" as const,
    icon: "🏛️",
    category: "history" as const,
    titleEn: "The Twelve Caesars",
    titleNl: "De Twaalf Caesars",
    subtitleEn: "Put the first 12 Roman emperors in chronological order",
    subtitleNl: "Zet de eerste 12 Romeinse keizers in chronologische volgorde",
    available: true,
    sortOrder: 1,
    items: [
      { position: 1,  name: "Julius Caesar",       imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Gaius_Iulius_Caesar_%28Vatican_Museum%29.jpg",                                                                                                                                                    dates: "49–44 BC",      fact: "Crossed the Rubicon in 49 BC, triggering a civil war that ended the Roman Republic.",                                                  descriptionEn: "Roman general and statesman who ended the Republic by seizing power. Assassinated on the Ides of March, 44 BC.",                                                                                                                                       descriptionNl: "Romeins veldheer en staatsman die de Republiek ten einde bracht. Vermoord op de Iden van Maart, 44 v.Chr." },
      { position: 2,  name: "Augustus",             imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Statue-Augustus.jpg/330px-Statue-Augustus.jpg",                                                                                                                                           dates: "27 BC–14 AD",   fact: "First Roman emperor; his 41-year reign was the longest of the Julio-Claudian dynasty.",                                                  descriptionEn: "Caesar's adopted heir who won the civil wars and became Rome's first true emperor. His reign brought the Pax Romana.",                                                                                                                                 descriptionNl: "Caesars geadopteerde erfgenaam die de burgeroorlogen won en Rome's eerste echte keizer werd. Zijn bewind bracht de Pax Romana." },
      { position: 3,  name: "Tiberius",             imageUrl: "https://ancientrome.ru/art/artwork/sculp/rom/imp/tiberius/tib021.jpg",                                                                                                                                                                               dates: "14–37 AD",      fact: "Spent the last decade of his reign in self-imposed exile on the island of Capri.",                                                      descriptionEn: "A capable general who became a reclusive ruler, retreating to Capri and leaving Rome governed by the feared Sejanus.",                                                                                                                                 descriptionNl: "Een bekwaam veldheer die een teruggetrokken heerser werd. Hij trok zich terug op Capri en liet Rome besturen door de gevreesde Sejanus." },
      { position: 4,  name: "Caligula",             imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Tiberius_Capri_Louvre_Ma1248.jpg/250px-Tiberius_Capri_Louvre_Ma1248.jpg",                                                                                                                dates: "37–41 AD",      fact: "Reputedly made his horse Incitatus a consul — though historians debate the story.",                                                      descriptionEn: "Initially popular, he descended into cruelty and erratic behaviour. Assassinated by his own Praetorian Guard after four years.",                                                                                                                      descriptionNl: "Aanvankelijk populair, verviel hij in wreedheid en grillig gedrag. Na vier jaar vermoord door zijn eigen Praetoriaanse Garde." },
      { position: 5,  name: "Claudius",             imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Claudius_Pio-Clementino_Inv243.jpg/960px-Claudius_Pio-Clementino_Inv243.jpg",                                                                                                            dates: "41–54 AD",      fact: "Conquered Britain in 43 AD and was likely poisoned by his wife Agrippina the Younger.",                                                    descriptionEn: "Considered a fool by his family, he proved a capable administrator. He conquered Britain and expanded Roman citizenship.",                                                                                                                             descriptionNl: "Door zijn familie als een dwaas beschouwd, bleek hij een bekwaam bestuurder. Hij veroverde Britannia en breidde het Romeins burgerschap uit." },
      { position: 6,  name: "Nero",                 imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Nero_Glyptothek_Munich_321.jpg/500px-Nero_Glyptothek_Munich_321.jpg",                                                                                                                    dates: "54–68 AD",      fact: "Last of the Julio-Claudians; famously blamed Christians for the Great Fire of Rome.",                                                     descriptionEn: "Last of the Julio-Claudians. Notorious for persecuting Christians and his artistic pretensions. Fled Rome and died by suicide.",                                                                                                                      descriptionNl: "De laatste Julio-Claudiër. Berucht om zijn vervolging van christenen en zijn artistieke pretenties. Vluchtte uit Rome en stierf door zelfdoding." },
      { position: 7,  name: "Galba",                imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Roman_emperor_Galba%2C_Gustav_III%27s_Museum_of_Antiquities%2C_Stockholm_%2820%29_%2835867773310%29_edited.jpg/500px-Roman_emperor_Galba%2C_Gustav_III%27s_Museum_of_Antiquities%2C_Stockholm_%2820%29_%2835867773310%29_edited.jpg", dates: "68–69 AD",      fact: "Ruled for only seven months; his refusal to pay promised bonuses led to his murder.",                                                      descriptionEn: "The first emperor not from Rome or Italy. His strict frugality alienated the army and he was murdered after just seven months.",                                                                                                                       descriptionNl: "De eerste keizer die niet uit Rome of Italië stamde. Zijn strenge zuinigheid vervreemdde het leger en hij werd na zeven maanden vermoord." },
      { position: 8,  name: "Otho",                 imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Statue_of_the_emperor_Otho%2C_Ma_1215_%28cropped1%29.jpg/500px-Statue_of_the_emperor_Otho%2C_Ma_1215_%28cropped1%29.jpg",                                                                dates: "Jan–Apr 69 AD", fact: "Reigned for just 95 days before taking his own life after the Battle of Bedriacum.",                                                     descriptionEn: "Former friend of Nero who seized power from Galba. He ruled for only 95 days before taking his own life after a military defeat.",                                                                                                                    descriptionNl: "Voormalig vriend van Nero die de macht van Galba overnam. Hij regeerde slechts 95 dagen en pleegde zelfmoord na een militaire nederlaag." },
      { position: 9,  name: "Vitellius",            imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Pseudo-Vitellius_Louvre_MR684.jpg/250px-Pseudo-Vitellius_Louvre_MR684.jpg",                                                                                                               dates: "Apr–Dec 69 AD", fact: "Known for his gluttony; reportedly spent a fortune on lavish banquets during his reign.",                                                   descriptionEn: "Known for lavish banquets and gluttony. His brief reign ended when Vespasian's forces defeated him and he was killed by a mob.",                                                                                                                       descriptionNl: "Bekend om weelderige banketten en vraatzucht. Zijn korte bewind eindigde toen Vespasianus' troepen hem versloegen en hij door een menigte werd gedood." },
      { position: 10, name: "Vespasian",            imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Vespasianus01_pushkin.jpg/330px-Vespasianus01_pushkin.jpg",                                                                                                                               dates: "69–79 AD",      fact: "Founded the Flavian dynasty and began construction of the Colosseum.",                                                                 descriptionEn: "A general of humble origin who restored stability after the Year of the Four Emperors and founded the Flavian dynasty.",                                                                                                                               descriptionNl: "Een generaal van bescheiden afkomst die stabiliteit herstelde na het Jaar van de Vier Keizers en de Flavische dynastie stichtte." },
      { position: 11, name: "Titus",                imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Titus%2C_Roman%2C_c._70_AD%2C_marble_-_Galleria_Borghese_-_Rome%2C_Italy_-_DSC04762.jpg/500px-Titus%2C_Roman%2C_c._70_AD%2C_marble_-_Galleria_Borghese_-_Rome%2C_Italy_-_DSC04762.jpg", dates: "79–81 AD",      fact: "Oversaw the destruction of Jerusalem and the eruption of Mount Vesuvius in 79 AD.",                                                      descriptionEn: "Beloved for his generosity, he oversaw the destruction of Jerusalem and responded admirably to the eruption of Vesuvius.",                                                                                                                             descriptionNl: "Geliefd om zijn vrijgevigheid. Hij leidde de verwoesting van Jeruzalem en reageerde bewonderenswaardig op de uitbarsting van de Vesuvius." },
      { position: 12, name: "Domitian",             imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Domitian.jpg/330px-Domitian.jpg",                                                                                                                                                         dates: "81–96 AD",      fact: "Last of the Twelve Caesars; his assassination led to the adoptive Antonine emperors.",                                                  descriptionEn: "An efficient but autocratic ruler who demanded to be called 'Lord and God'. His assassination ended the Flavian dynasty.",                                                                                                                             descriptionNl: "Een efficiënte maar autocratische heerser die eiste 'Heer en God' genoemd te worden. Zijn moord beëindigde de Flavische dynastie." },
    ],
  },
  {
    slug: "conquistadors",
    gameType: "chronology" as const,
    icon: "⚔️",
    category: "history" as const,
    titleEn: "The Conquistadors",
    titleNl: "De Conquistadors",
    subtitleEn: "Order these Spanish conquistadors chronologically by their defining expedition",
    subtitleNl: "Zet deze Spaanse conquistadors in chronologische volgorde van hun bepalende expeditie",
    available: true,
    sortOrder: 2,
    items: [
      { position: 1, name: "Christopher Columbus",  imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Christopher_Columbus.PNG/500px-Christopher_Columbus.PNG",                                                                                          dates: "c.1451–1506", fact: "Reached the Americas in 1492 while sailing west for Spain, opening the New World to European colonisation.",                                                          descriptionEn: "Genoese navigator who sailed for Spain and reached the Americas in 1492, opening the era of European exploration and colonisation.",                                                                                                              descriptionNl: "Genuese zeevaarder die voor Spanje voer en in 1492 Amerika bereikte, waarmee hij het tijdperk van Europese verkenning en kolonisatie inluidde." },
      { position: 2, name: "Vasco Núñez de Balboa", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Retrato_de_Vasco_Nu%C3%B1ez_de_Balboa_%281475-1517%29_-_An%C3%B3nimo.jpg/960px-Retrato_de_Vasco_Nu%C3%B1ez_de_Balboa_%281475-1517%29_-_An%C3%B3nimo.jpg", dates: "c.1475–1519", fact: "Crossed the Isthmus of Darién in 1513 and became the first European to see the Pacific Ocean from the Americas.",                                      descriptionEn: "First European to see the Pacific Ocean from the Americas after crossing the Isthmus of Darién in 1513, claiming the sea for Spain.",                                                                                                            descriptionNl: "De eerste Europeaan die de Stille Oceaan vanuit Amerika zag na het oversteken van de landengte van Darién in 1513, en de zee voor Spanje opeiste." },
      { position: 3, name: "Hernán Cortés",         imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/06/Retrato_de_Hern%C3%A1n_Cort%C3%A9s.jpg",                                                                                                               dates: "1485–1547",   fact: "Conquered the Aztec Empire in 1519–1521, bringing the most powerful civilisation in Mesoamerica under Spanish rule.",                                       descriptionEn: "Led the Spanish conquest of the Aztec Empire between 1519 and 1521, toppling Tenochtitlán and claiming Mexico for the Spanish Crown.",                                                                                                           descriptionNl: "Leidde de Spaanse verovering van het Azteekse Rijk tussen 1519 en 1521, veroverde Tenochtitlán en claimde Mexico voor de Spaanse kroon." },
      { position: 4, name: "Francisco Pizarro",     imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Portrait_of_Francisco_Pizarro.jpg/330px-Portrait_of_Francisco_Pizarro.jpg",                                                                       dates: "c.1471–1541", fact: "Toppled the Inca Empire in the 1530s by capturing Emperor Atahualpa and extorting a roomful of gold and silver as ransom.",                               descriptionEn: "Conquered the Inca Empire in the 1530s with a small force, capturing Emperor Atahualpa and claiming vast Andean territories for Spain.",                                                                                                         descriptionNl: "Veroverde het Incarijk in de jaren 1530 met een kleine troepenmacht, greep keizer Atahualpa en claimde uitgestrekte Andesgebieden voor Spanje." },
      { position: 5, name: "Diego de Almagro",      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/70/Diego_de_Almagro.JPG?_=20180421094203",                                                                                                                  dates: "c.1475–1538", fact: "Co-led the conquest of Peru with Pizarro, then braved a 10,000-km round trip to Chile in 1535–36 in search of a second golden empire.",               descriptionEn: "Partner of Pizarro in the Peru conquest; later led a gruelling expedition to Chile in 1535–36, finding little gold and returning defeated.",                                                                                                     descriptionNl: "Partner van Pizarro bij de verovering van Peru; leidde later een uitputtende expeditie naar Chili in 1535–36, vond weinig goud en keerde verslagen terug." },
      { position: 6, name: "Pedro de Valdivia",     imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Pedro_de_Valdivia.jpg/500px-Pedro_de_Valdivia.jpg",                                                                                               dates: "c.1497–1553", fact: "Founded Santiago and a string of Chilean cities from 1541 onward; killed in a Mapuche ambush led by the chief Caupolicán.",                               descriptionEn: "Conquered and settled Chile from 1540 onward, founding Santiago and other cities before being killed in battle with the Mapuche in 1553.",                                                                                                       descriptionNl: "Veroverde en koloniseerde Chili vanaf 1540, stichtte Santiago en andere steden voordat hij in 1553 in gevecht met de Mapuche sneuvelde." },
      { position: 7, name: "Gonzalo Pizarro",       imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/96/Gonzalo_Pizarro.jpg",                                                                                                                                    dates: "c.1510–1548", fact: "Led 4,000 men into the Amazon basin in 1541 hunting El Dorado; the expedition collapsed, but it set the stage for Orellana's journey.",               descriptionEn: "Half-brother of Francisco Pizarro who led a disastrous expedition east of the Andes in 1541–42 searching for El Dorado and the Land of Cinnamon.",                                                                                              descriptionNl: "Halfbroer van Francisco Pizarro die in 1541–42 een rampzalige expeditie ten oosten van de Andes leidde op zoek naar El Dorado en het Kaneelland." },
      { position: 8, name: "Francisco de Orellana", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRs6npWfM_HV7SWUES9mPCusVQkwF27_VIZlyIOwKImUb_zG_3Ei-dy8F0A7MhPVmT4Mt-cA4Agf2I6jrgd8PfAgFYmTwo92xRJZC13nLWi&s=10",                                 dates: "c.1511–1546", fact: "Broke away from Gonzalo Pizarro's starving column in 1541 and floated the entire length of the Amazon River to the Atlantic — a 6,000-km first.", descriptionEn: "Separated from Gonzalo Pizarro's expedition and in 1541–42 became the first European to navigate the entire length of the Amazon River.",                                                                                                    descriptionNl: "Scheidde zich af van Gonzalo Pizarro's expeditie en werd in 1541–42 de eerste Europeaan die de volledige Amazone-rivier bevuhr." },
    ],
  },
  {
    slug: "quantum-scientists",
    gameType: "chronology" as const,
    icon: "🔬",
    category: "science" as const,
    titleEn: "Quantum Scientists",
    titleNl: "Kwantumwetenschappers",
    subtitleEn: "Order the key scientists of quantum mechanics by their defining contribution",
    subtitleNl: "Zet de sleutelwetenschappers van de kwantummechanica in volgorde van hun bepalende bijdrage",
    available: true,
    sortOrder: 3,
    items: [
      { position: 1, name: "Max Planck",        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Max_Planck_by_Hugo_Erfurth_1938cr_-_restoration1.jpg/500px-Max_Planck_by_Hugo_Erfurth_1938cr_-_restoration1.jpg", dates: "1858–1947", fact: "Introduced the concept of the quantum in 1900, proposing that energy is emitted in discrete packets to explain blackbody radiation.",           descriptionEn: "Solved the blackbody radiation problem in 1900 by proposing that energy is emitted in discrete packets — quanta. This act of 'desperation' launched quantum theory.",                                                                    descriptionNl: "Loste het probleem van zwartlichaamsstraling op in 1900 door voor te stellen dat energie in discrete pakketten — quanta — wordt uitgestraald. Deze 'wanhoopsdaad' leidde de kwantumtheorie in." },
      { position: 2, name: "Albert Einstein",   imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Albert_Einstein_Head.jpg/330px-Albert_Einstein_Head.jpg",                                                            dates: "1879–1955", fact: "Explained the photoelectric effect in 1905 using photons, providing the first concrete evidence for Planck's quantum hypothesis.",                 descriptionEn: "Explained the photoelectric effect in 1905 using light quanta (photons), for which he received the Nobel Prize. Also showed that mass and energy are interchangeable.",                                                                    descriptionNl: "Verklaarde het foto-elektrisch effect in 1905 met behulp van lichtquanta (fotonen), waarvoor hij de Nobelprijs ontving. Toonde ook aan dat massa en energie uitwisselbaar zijn." },
      { position: 3, name: "Niels Bohr",        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Niels_Bohr.jpg/330px-Niels_Bohr.jpg",                                                                               dates: "1885–1962", fact: "Proposed quantised electron orbits in 1913, explaining why atoms emit light at specific wavelengths and launching modern atomic theory.",          descriptionEn: "Proposed in 1913 that electrons orbit the nucleus in fixed quantised energy levels, explaining atomic spectra. Later led the Copenhagen interpretation of quantum mechanics.", descriptionNl: "Stelde in 1913 voor dat elektronen de kern omcirkelen in vaste gekwantiseerde energieniveaus, waarmee atomaire spectra werden verklaard. Leidde later de Kopenhagen-interpretatie van de kwantummechanica." },
      { position: 4, name: "Louis de Broglie",  imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d2/Broglie_Big.jpg",                                                                                                          dates: "1892–1987", fact: "Proposed in 1924 that all matter has wave-like properties, extending wave–particle duality from light to electrons and all particles.",          descriptionEn: "Proposed in his 1924 PhD thesis that all matter has an associated wave, extending wave-particle duality beyond light and earning him a Nobel Prize five years later.",       descriptionNl: "Stelde in zijn proefschrift van 1924 voor dat alle materie een bijbehorende golf heeft, waarmee golff-deeltjesdualiteit verder reikte dan licht. Dit leverde hem vijf jaar later een Nobelprijs op." },
      { position: 5, name: "Werner Heisenberg", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f8/Bundesarchiv_Bild183-R57262%2C_Werner_Heisenberg.jpg",                                                                     dates: "1901–1976", fact: "Formulated matrix mechanics in 1925 and the uncertainty principle in 1927 — you cannot simultaneously know a particle's exact position and momentum.", descriptionEn: "Formulated matrix mechanics — the first complete version of quantum mechanics — in 1925, and in 1927 stated the uncertainty principle: position and momentum cannot both be precisely known.", descriptionNl: "Formuleerde matrixmechanica — de eerste volledige versie van kwantummechanica — in 1925, en stelde in 1927 het onzekerheidsbeginsel: positie en impuls kunnen niet beide precies bekend zijn." },
      { position: 6, name: "Erwin Schrödinger", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Erwin_Schr%C3%B6dinger_%281933%29.jpg/330px-Erwin_Schr%C3%B6dinger_%281933%29.jpg",                                  dates: "1887–1961", fact: "Developed wave mechanics and the Schrödinger equation in 1926, the central equation governing how quantum states evolve over time.",            descriptionEn: "Developed wave mechanics and the Schrödinger equation in 1926, describing how quantum states evolve. His thought experiment about a cat in a box became an icon of quantum weirdness.", descriptionNl: "Ontwikkelde golfmechanica en de Schrödinger-vergelijking in 1926, die beschrijft hoe kwantumtoestanden evolueren. Zijn gedachte-experiment over een kat in een doos werd een icoon van kwantumvreemdheid." },
      { position: 7, name: "Max Born",          imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Max_Born.jpg/500px-Max_Born.jpg",                                                                                    dates: "1882–1970", fact: "Gave the wave function its probabilistic meaning in 1926 — its squared amplitude gives the probability of finding a particle at a given place.",   descriptionEn: "Provided the probabilistic interpretation of Schrödinger's wave function in 1926: the square of the amplitude gives the probability of finding a particle at a location.",  descriptionNl: "Gaf in 1926 de probabilistische interpretatie van Schrödingers golffunctie: het kwadraat van de amplitude geeft de kans om een deeltje op een locatie aan te treffen." },
      { position: 8, name: "Paul Dirac",        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8a/Paul_Dirac%2C_1933%2C_head_and_shoulders_portrait%2C_bw.jpg",                                                             dates: "1902–1984", fact: "Combined quantum mechanics with special relativity in the Dirac equation (1928), which predicted the existence of antimatter.",                    descriptionEn: "Unified quantum mechanics and special relativity in the Dirac equation (1928), which predicted the existence of antimatter — confirmed four years later with the discovery of the positron.", descriptionNl: "Verenigde kwantummechanica en speciale relativiteitstheorie in de Dirac-vergelijking (1928), die het bestaan van antimaterie voorspelde — vier jaar later bevestigd met de ontdekking van het positron." },
    ],
  },
  {
    slug: "olympics",
    gameType: "puzzle" as const,
    icon: "🏅",
    category: "other" as const,
    titleEn: "The Olympics",
    titleNl: "De Olympische Spelen",
    subtitleEn: "Reassemble the portraits of legendary Olympic champions",
    subtitleNl: "Herstel de portretten van legendarische olympische kampioenen",
    available: true,
    sortOrder: 4,
    items: [
      { position: 1, name: "Usain Bolt",      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/33/Usain_Bolt_2012_Olympics_1.jpg",                                                               hint: "Athletics · Jamaica",               achievement: "9 Olympic gold medals (2008 · 2012 · 2016)",                        descriptionEn: "Jamaican sprinter widely regarded as the greatest of all time. He set the 100 m world record of 9.58 s in 2009 — a mark that still stands. His triple-triple (100 m, 200 m, 4×100 m relay gold at three consecutive Olympics) has never been matched.",                                                                                                                                                                     descriptionNl: "Jamaicaanse sprinter die algemeen wordt beschouwd als de beste ooit. Hij vestigde het wereldrecord op de 100 m van 9,58 seconden in 2009 — een record dat nog steeds staat. Zijn triple-triple (100 m, 200 m en 4×100 m estafette goud op drie opeenvolgende Olympische Spelen) is nooit geëvenaard." },
      { position: 2, name: "Michael Phelps",  imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c8/Michael_Phelps_2012.jpg?_=20160812051555",                                                    hint: "Swimming · USA",                   achievement: "23 Olympic gold medals — the most decorated Olympian of all time", descriptionEn: "American swimmer and the most decorated Olympian in history, with 28 Olympic medals (23 gold). Competing across five Games from Sydney 2000 to Rio 2016, he won eight golds in a single Games (Beijing 2008), a record in itself.",                                                                                                                                                                                     descriptionNl: "Amerikaans zwemmer en de meest gedecoreerde Olympiër in de geschiedenis, met 28 Olympische medailles (23 goud). Actief op vijf Spelen van Sydney 2000 tot Rio 2016, won hij acht gouden medailles op één Spelen (Peking 2008), op zichzelf al een record." },
      { position: 3, name: "Simone Biles",    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/74/Simone_Biles_Rio_2016e.jpg",                                                                  hint: "Artistic Gymnastics · USA",        achievement: "7 Olympic gold medals (2016 · 2024)",                               descriptionEn: "American artistic gymnast and the most decorated gymnast in World Championship history. She won four gold medals at Rio 2016 and added three more at Paris 2024 aged 27, cementing her status as the greatest gymnast of all time.",                                                                                                                                                                                           descriptionNl: "Amerikaans artistiek turnster en de meest gedecoreerde gymnast in de geschiedenis van de Wereldkampioenschappen. Ze won vier gouden medailles op Rio 2016 en voegde er op 27-jarige leeftijd nog drie toe op Parijs 2024, waarmee ze haar status als de grootste gymnaste aller tijden bevestigde." },
      { position: 4, name: "Carl Lewis",      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Carl_Lewis_2011_Shankbone.JPG",                                                               hint: "Athletics · USA",                  achievement: "9 Olympic gold medals (1984 · 1988 · 1992 · 1996)",                descriptionEn: "American sprinter and long jumper who dominated track and field for over a decade. He matched Jesse Owens's legendary four-gold haul at a single Games (Los Angeles 1984) and defended his long jump title at four consecutive Olympics.",                                                                                                                                                                                      descriptionNl: "Amerikaans sprinter en verspringer die de atletiek meer dan een decennium domineerde. Hij evenaarde Jesse Owens' legendarische vier gouden medailles op één Spelen (Los Angeles 1984) en verdedigde zijn verspringtitel op vier opeenvolgende Olympische Spelen." },
      { position: 5, name: "Nadia Comaneci",  imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/72/Nadia_Com%C4%83neci_1976b.jpg",                                                              hint: "Artistic Gymnastics · Romania",    achievement: "5 Olympic gold medals · First gymnast to score a perfect 10 (1976)", descriptionEn: "Romanian gymnast who, at just 14 years old, became the first athlete in Olympic history to be awarded a perfect score of 10.0 at the 1976 Montreal Games. The scoreboard wasn't even designed to display a 10 — it showed 1.00 instead.",                                                                                                                                                                              descriptionNl: "Roemeense turnster die op slechts 14-jarige leeftijd de eerste atleet in de olympische geschiedenis werd die een perfecte score van 10,0 ontving op de Spelen van Montreal 1976. Het scorebord was niet eens ontworpen om een 10 te tonen — het gaf 1,00 weer." },
      { position: 6, name: "Mark Spitz",      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Mark_Spitz_1972c.jpg/960px-Mark_Spitz_1972c.jpg?_=20170720070216",                    hint: "Swimming · USA",                   achievement: "9 Olympic gold medals · 7 golds in a single Games (Munich 1972)",   descriptionEn: "American swimmer who won seven gold medals at the Munich 1972 Olympics — each in world record time — a feat that stood as the record for most golds in a single Games for 36 years until Michael Phelps won eight in Beijing.",                                                                                                                                                                                         descriptionNl: "Amerikaans zwemmer die zeven gouden medailles won op de Olympische Spelen van München 1972 — elk in wereldrecordtijd — een prestatie die 36 jaar lang het record bleef voor de meeste gouden medailles op één Spelen, totdat Michael Phelps er acht won in Peking." },
    ],
  },
];

/** Seed challenge games and items if the tables are empty. */
export function seedChallenges(db: BetterSQLite3Database) {
  const existing = db.select().from(challengeGames).all();
  if (existing.length > 0) return;

  console.log("  Seeding challenge games...");
  for (const game of games) {
    const { items, ...gameData } = game;
    const [inserted] = db.insert(challengeGames).values(gameData).returning({ id: challengeGames.id }).all();
    const gameId = inserted.id;

    for (const item of items) {
      db.insert(challengeItems).values({ gameId, ...item }).run();
    }
    console.log(`    ✓ ${game.slug} (${items.length} items)`);
  }
  console.log("  Challenge games seeded.");
}
